apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tower
    app.kubernetes.io/name: tower
  name: tower
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tower
      app.kubernetes.io/name: tower
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tower
        app.kubernetes.io/name: tower
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tower
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /proxy
            - --ca-cert=/ca.crt
            - --ca-key=/ca.key
            - --v=4
            - --leader-elect=true
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
