apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
  name: tower
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: tower
  sessionAffinity: None
  type: LoadBalancer
