name: ci
on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
jobs:
  ci:
    name: Lint and unit test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Environment
        run: |
          go version
          go env
      - name: Lint
        run: make lint
      - name: Test
        run: make test
